### ISSUE TITLE
slow build for vuepress serve when using markdown-it-texmath

### ISSUE THREAD

**Issue by songololo** [goessner/markdown-it-texmath#13]
I am not sure if this would be a [`vuepress`](https://github.com/vuejs/vuepress) or `markdown-it-texmath` issue. Vuepress is a static site generator that uses `markdown-it` to render HTML content.

The `vuepress` dev server starts-up really slowly when using `markdown-it-texmath`, though regular builds (for production) are not as slow. It seems that they are using `webpack-dev-server` under the hood. After the initial build, subsequent refreshes are quicker, i.e. they seem to be using some sort of cache.

I'm not sure how to go about debugging this, but any ideas on what the hold-up might be or suggestions for where to look?

**Comment by songololo** [comment]
I've created a minimal example here: [`markdown-katex-debug`](https://github.com/songololo/markdown-katex-debug).

And opened a similar issue in the `katex` repo:
https://github.com/KaTeX/KaTeX/issues/1865

**Comment by janvorisek** [comment]
I ran into the same issue. Build almost freezes with `webpack-dev-server` using default `vuepress dev`. Finishes after 30 min.

**Comment by songololo** [comment]
@janvorisek I'm not aware of any solutions to above but the new [`vuepress-plugin-mathjax`](https://github.com/vuepress/vuepress-plugin-mathjax) might work for your purposes?

**Comment by janvorisek** [comment]
@songololo Yeah that one is working, but i personally prefer KaTeX as it's faster, resulting math is partially selectable and it supports tagging using `\tag`. 

I just found out that mathjax supports at least equation numbering which I need so thank you anyway :-)

Hopefully someone will fix the issue soon so we can switch to KaTeX.

**Comment by goessner** [comment]
I do not use `vuepress` and don't intend to do so in near future.

So I definitely need your help here with that issue ... some new insights ?

**Comment by goessner** [comment]
Closed due to inactivity ... can be reopened again.
