### ISSUE TITLE
double dollar delimiter doesn't seem to work in markdown tables?

### ISSUE THREAD

**Issue by songololo** [goessner/markdown-it-texmath#14]
Is there a way to use double dollar (display style) delimiters in tables?

e.g., this doesn't work:
```
| key | formula | notes |
|-----|---------|-------|
| node_density | $$\sum_{j\neq{i}} w_{j}$$ | The default $w=1$ reduces ... |
```

But the single-dollar (inline) delimiter still seems to work fine.

**Comment by goessner** [comment]
Unfortunately we cannot use block elements inside of tables with markdown ... [see](https://www.markdownguide.org/extended-syntax/#tables).

This is the reason, why display style (block) equations don't work in tables.

thanks
