### ISSUE TITLE
feature request: adding a rule for Julia Markdown

### ISSUE THREAD

**Issue by isaacsas** [goessner/markdown-it-texmath#15]
Julia's [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl) package uses ` $...$ ` and ` ``.. .`` ` for inline markdown math, and ` ```math ... ```  ` for blocks. 

Is there any possibility of adding this mix as an option? I know I can modify this locally, but I'm using a VSCode extension that bundles markdown-it-texmath to highlight Julia markdown files, and the extension can overwrite my changed texmath.js file when it updates...

**Comment by goessner** [comment]
now - after finding time at last for this - I implemented and tested your proposed rule for Julia markdown.

It seems to work. Use Version 0.6.0 now.

Please also test and tell me about possible bugs.

Thanks

**Comment by isaacsas** [comment]
Thanks! I made a similar change to the texmath.js file distributed with mdmath a while back and have had no issues. I'll be happy to be able to go back to not having to use a modded file.
