### ISSUE TITLE
Change "'dollar'" to "dollar" in settings.json

### ISSUE THREAD

**Issue by myoung-space-science** [goessner/markdown-it-texmath#17]
I had to change `"mdmath.delimiters": "'dollars'"` to `"mdmath.delimiters": "dollars"` (i.e., remove single quotes within double quotes around dollars) in settings.json in order to render as expected math in VS Code on Ubuntu 18.04. Before removing the single quotes, TeX syntax just showed up as typed in the source.

Before:
![mdmath-before](https://user-images.githubusercontent.com/54921342/64629809-e2e02500-d3c1-11e9-87f5-a80e409dd091.png)

After:
![mdmath-after](https://user-images.githubusercontent.com/54921342/64629822-e83d6f80-d3c1-11e9-8c51-51db46d2dfe6.png)

**Comment by goessner** [comment]
This is not a `markdown-it-texmath` issue, but an [`mdmath`](https://github.com/goessner/mdmath) one.

I will have a look at that issue there ...

thanks
