### ISSUE TITLE
Custom math delimiters

### ISSUE THREAD

**Issue by AWConant** [goessner/markdown-it-texmath#2]
Is it possible to define your own math delimiters? I'm currently writing for a site that requires _all_ LaTeX (both inline and multiline) to be delimited by double dollar signs, but I can't figure out how (or if it's even possible) to do so.

**Comment by goessner** [comment]
Yes, you can simply extend the `texmath.rules` object in `texmath.js`.

Might be something like ...

```js
texmath.rules.custom = {
      inline: [
           { /* 1st inline rule */ },
           { /* 2nd optional inline rule */ }
      ],
      block [
           { /* 1st block rule */ },
           { /* 2nd optional block rule */ }
      ]
}
``` 
See `texmath.js` for details and examples.

**Comment by AWConant** [comment]
Nice, thanks. I simply copypasted the "dollars" object, changed its name, and changed the following in "math_inline" and "math_single":

- add {2} after each \$ in rex
- change tag from "$" to "$$"

Seems to work.

**Comment by goessner** [comment]
cool .. thanks
