### ISSUE TITLE
Katex duplicates text

### ISSUE THREAD

**Issue by MurelloS** [goessner/markdown-it-texmath#20]
I used the library 3 weeks ago, and it worked very well.
I started refactoring, updated libraries, and there was a problem.
Katex parameters are duplicated as text.

```css
<span class="katex">
    <span class="katex-mathml"></span>
    <span class="katex-html" aria-hidden="true"></span>
</span>

```

it turns out that something like this ~~ABC~~ABC

**Comment by MurelloS** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/48526767/80796183-ff7ed680-8bb7-11ea-9c6b-15eabb0ccdff.png)

**Comment by goessner** [comment]
This effect most likely occurs because of missing / invalid css styles. Please ensure to have access to

```html
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/markdown-it-texmath/css/texmath.min.css">
```

or their local (full) counterparts.

**Comment by goessner** [comment]
... assuming to be resolved ...

**Comment by lushangkan** [comment]
I had this problem too, and eventually solved it by import katex/dist/katex.css
