### ISSUE TITLE
Custom delimiter option

### ISSUE THREAD

**Issue by iranvir** [goessner/markdown-it-texmath#27]
### Feature Request
Hello, I was wondering if it would be possible to use `\\[`  `\\]` and `\\(` and `\\)` as delimiters instead of their single backslash counterparts.
I am using Hugo to render my website and it uses `\` as an escape character. So my markdown texts need `\\[` as a delimiter for MathJAX (within Hugo) to recieve `\[`

**Comment by sprajagopal** [comment]
Hi, could you please expand on how to set custom delimiters? I went through [this thread](https://github.com/goessner/markdown-it-texmath/issues/2) but I couldn't get it working:

I added this to the texmath.js variable `texmath.rules`
```
...,
hugo: {
        inline: [ 
            {   name: 'math_inline',
                rex: /\\\\((.+?)\\\\)/gy,
                tmpl: '<eq>$1</eq>',
                tag: '\\\('
            }
        ],
        block: [
            {   name: 'math_block_eqno',
                rex: /\\\\[(((?!\\\\]|\\\\[)[\s\S])+?)\\\\]\s*?\(([^)$\r\n]+?)\)/gmy,
                tmpl: '<section class="eqno"><eqn>$1</eqn><span>($2)</span></section>',
                tag: '\\\['
            },
            {   name: 'math_block',
                rex: /\\\\[([\s\S]+?)\\\\]/gmy,
                tmpl: '<section><eqn>$1</eqn></section>',
                tag: '\\\['
            }
        ]
    },
...
```
but it still seems to render on dollars only.

**Comment by goessner** [comment]
hmm ... don't forget to address your rules explicitely ...

```js
const md = require('markdown-it')({html:true})
                  .use(tm, { engine: require('katex'),
                             delimiters: 'hugo',
                             katexOptions: {} });
```
