### ISSUE TITLE
Cannot include escaped dollar when using dollars delimiters

### ISSUE THREAD

**Issue by rogino** [goessner/markdown-it-texmath#32]
The regex for dollar delimiters breaks if the content includes an escaped dollar (`\$`), making it impossible to type dollar literals inside math blocks:

```
$$
\$10.00
$$

$\$10.00$
```

will all fail to be parsed as a latex block.

Workarounds include using a different delimiter style or use `\text{\textdollar}`, but getting it to work without these would be nice.

I've been to update the `math_block` regex from:

`/\${2}([^$]+?)\${2}/gmy` to

`/\${2}((?:\\\$|[^$])+?)\${2}/gmy`

but it doesn't cover all cases, and I haven't been able to figure out where to start with the `math_inline` regex.

**Comment by goessner** [comment]
Sorry for the delay. Thanks for your valuable input.

>     * `math_inline_double` still uses `.`; should probably switch that to `[^]` too.

math_inline should be written on a single line, but I added it to be more forgiving here.
> 
>     * I think you can use `[^\s\\]` instead of `[^\r\n\t\f\v \\]`. (The behavior is slightly different: the former treats all Unicode space identically. Probably better?)

This is definitely better ... taken.

> 
>     * `[^]+?[^\\]` (which occurs in both block rules) seems to require at least two characters.  Should probably be `[^]*?[^\\]`.

Yes ... thanks for catching.

> 
>     * Shouldn't `math_inline_double` have the same addition to exclude a trailing `\`?

sure ... done.

> 
>     * `\$((?:[^\r\n\t\f\v \\])|(?:\S.*?[^\r\n\t\f\v \\]))\$` can be simplified to `\$([^\r\n\t\f\v \\]|\S.*?[^\r\n\t\f\v \\])\$` or `\$([^\s\\]|\S.*?[^\s\\])\$`. (I'm not quite sure why you're forbidding spaces next to the `$`s but I assume that's intentional, to avoid some stray matching.)

yes ... again a significant improvement.

> Nested `$`s are for re-entering math mode. `\text{$x+y$}` is different from `\text{\$x+y\$}`:
> So it's not possible to escape these instances of `$`, as `\$` means something in LaTeX.

Now I understand that reentering math mode effect. Escaping makes no sense indeed. I still consider it a not so relevant edge case in practise. I don't want to invest that significant implementation effort at current. A PR is always welcome though.

thanks again ...
