### ISSUE TITLE
$$x^2$$ drops the 2

### ISSUE THREAD

**Issue by edemaine** [goessner/markdown-it-texmath#35]
I'm guessing this is from the new regexes: in `dollars` mode, `$$x^2$$` omits the `2` when calling KaTeX, so doesn't render.

It looks like `/\${2}([^]*?)[^\\]\${2}/gy` should be `/\${2}([^]*?[^\\])\${2}/gy`.

Maybe worth double-checking the other regexes.

**Comment by goessner** [comment]
good catch ... copy/paste to wrong position ... fixed with version 0.9.6

other regexes checked.

thanks

**Comment by edemaine** [comment]
Thanks! It works great now.
