### ISSUE TITLE
Suggestion: enable more than 1 delimiter.

### ISSUE THREAD

**Issue by tomasrei** [goessner/markdown-it-texmath#37]
I believe you can't use more than 1 delimiter atm? I usually use $ for inline math and \[...\] for display math. It would be great if you could use both! Thanks.

**Comment by goessner** [comment]
Would you like to use $ and [...] for both ... ? You know that delimiters for inline and display math usually are different ? See the readme ...

**Comment by tomasrei** [comment]
Sorry, I was maybe a bit unclear.  I would like to use $ for inline math and brackets /\[.../\] for display math. The reason being that I find it a bit messy to use /\(.../\) inline. As I understand it, it's either or at the moment?

**Comment by goessner** [comment]
Sorry, an individual combination of inline and display math delimiters is not supported. Please choose one syntax documented in

https://github.com/goessner/markdown-it-texmath
