### ISSUE TITLE
Space out immediately after the left dollar

### ISSUE THREAD

**Issue by NoSuke23** [goessner/markdown-it-texmath#38]
If spaces are after the left dollar, the string isn't parse to TeX math.

```js
md().use(tm).render("$a$") // <p><eq>...</eq></p>
md().use(tm).render("$ a$") // <p>$ a$</p> 
```

**Comment by goessner** [comment]
This is by intention to allow markup using `$`'s besides math:
```md
It costs 5$ or 8$.
```
So with inline math leading and trailing spaces are not allowed.

**Comment by NoSuke23** [comment]
I got it. Sorry, but I have one more question about the following.

```js
md().use(tm).render("$hoges$") // <p>$hoges$</p> 
md().use(tm).render("$hoges $") // <p><eq>...</eq></p>
```

If there is "s" before the last `$`, it's not too.

**Comment by goessner** [comment]
oops ... can't reproduce. Would you please be so kind and check, if you use the latest version "0.9.7" ?

**Comment by NoSuke23** [comment]
please see [here](https://codesandbox.io/s/proud-breeze-dg6ib?file=/src/index.js).

**Comment by goessner** [comment]
cool ... please switch to current version "0.9.7" ...

**Comment by NoSuke23** [comment]
Isn't the latest version "0.9.6" ?

**Comment by goessner** [comment]
just verified, that  "0.9.7" wasn't published yet ... now it is ... sorry.

**Comment by NoSuke23** [comment]
it worked! thank you for your work.
