### ISSUE TITLE
Option to support multiple delimiters

### ISSUE THREAD

**Issue by tlylt** [goessner/markdown-it-texmath#40]
Hi,
I am using `markdown-it-texmath` in a project(Thank you!) with 'bracket' as the delimiter. Would like to ask if it is currently possible for users to specify more than one of the supported delimiters to use interchangeably. 
E.g. possible to do something like `delimiters: ['dollars', 'brackets']` ? 
```js
const tm = require('markdown-it-texmath');
const md = require('markdown-it')({html:true})
                  .use(tm, { engine: require('katex'),
                             delimiters: 'dollars', 
                             katexOptions: { macros: {"\\RR": "\\mathbb{R}"} } });
```
Thanks!

**Comment by tlylt** [comment]
Found a convenient but somewhat hacky solution of requiring the plugin twice.
```js
markdownIt.use(require('markdown-it-mark'))
	//...
  .use(require('markdown-it-texmath'), { engine: katex, delimiters: 'brackets' })
  .use(require('markdown-it-texmath'))
```

**Comment by goessner** [comment]
Support of simultaneous use of multiple delimiters now with Version 1.0 . Thanks for proposing.
