### ISSUE TITLE
Why not add katex and markdown-it as dependency?

### ISSUE THREAD

**Issue by wafer-li** [goessner/markdown-it-texmath#5]
Since it requires `katex` and `markdown-it`, I think it had better add katex and markdown-it in `dependencies` not `devDependencies`

**Comment by goessner** [comment]
I prefer to leave it to the responsibility of the environment (like `mdmath`) using `markdown-it-texmath` and possibly other  `markdown-it-xxx` plugins to care about the proper addition of `markdown-it`.

Then you can decide to include `katex` as well, or alternatively another TeX rendering module.  `markdown-it-texmath` is basically designed so, that it should be able to function properly with other rendering libraries (in future) also.

The question `dependencies` vs `devDependencies`  discussed controversly here
[here](https://github.com/webpack/webpack/issues/520) and [there](https://stackoverflow.com/questions/19339227/bower-and-devdependencies-vs-dependencies/19341028#19341028).

Please note, as  `devDependencies`  is more liberal, 
> ... there is no way to omit modules listed under dependencies.

thanks

**Comment by wafer-li** [comment]
OK，I see.
