### ISSUE TITLE
change line issue

### ISSUE THREAD

**Issue by jdily** [goessner/markdown-it-texmath#6]
Hi, I am wondering how to insert a change line in math environment?
I am using delimeter $$ and want to write a two line equation.
However, the symbol // just broke the mathmode..

thx for help 👍

**Comment by goessner** [comment]
seems to be a KaTeX [issue](https://github.com/Khan/KaTeX/issues/171) ... should work in `aligned` environment.

**Comment by jdily** [comment]
thx for the reply.
hmmm, I fail to use `aligned ` in the markdown + math plugin for visual studio...

**Comment by jdily** [comment]
ah I just figure it out seems my vs code is bit outdated...
thx a lot for pointing out the possible solution :)

**Comment by goessner** [comment]
yes ...
```
$$
\begin{aligned}
    x &= y^2 \\
    x &= z + 2^t
\end{aligned}
$$
```
should work as expected ...
