### ISSUE TITLE
$$ for Math Inline to be compatible with Kramdown

### ISSUE THREAD

**Issue by varunagrawal** [goessner/markdown-it-texmath#7]
Thanks for the great work with this package.

Currently, Kramdown with Mathjax only supports $$ for both inline and block latex rendering, since the argument is that a $ is too pervasive and might inadvertently convert to latex what wasn't supposed to be converted e.g. `$25 worth of fruits`.

It would be nice to have the option of putting inline math as $$ so that one can then publish the Markdown file to a Jekyll page directly.

**Comment by Ray-Eldath** [comment]
Absolutely reasonable... I think could provide an option to config which identifier to match.

**Comment by goessner** [comment]
I finally had a chance to have a closer look into that. It seems to work fine after implementing.

Simply specify the `options` argument `{delimiters:'kramdown'}` for having [Kramdown](https://kramdown.gettalong.org/) support now.

Will update `mdmath` with that in near future.

Thanks.
